site_name: Ingenieria en Software :")
dev_addr: 127.0.0.1:8001
# site_url: 
# repo_url: 
# repo_name: <i class="fa fa-git"></i>

theme:
    name: mkdocs
    custom_dir: resources/
extra_css:
    - css/page.css
nav:
    - Individuales:
        - Actividad 1: individual/actividad1.md
        - Actividad 2: individual/actividad2.md
        - Actividad 3: individual/actividad3.md
        - Actividad 4: individual/actividad4.md
    - Colaborativas:
        - Actividad 1: todo.md
copyright: ©GMDXX
site_author: GMDXX
